2023-05-10 08:37:53,995 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.128:39737'
2023-05-10 08:38:01,993 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.128:37079
2023-05-10 08:38:01,993 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.128:37079
2023-05-10 08:38:01,993 - distributed.worker - INFO -           Worker name:             SLURMCluster-5
2023-05-10 08:38:01,993 - distributed.worker - INFO -          dashboard at:         172.16.3.128:35516
2023-05-10 08:38:01,993 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.56:37266
2023-05-10 08:38:01,993 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:38:01,993 - distributed.worker - INFO -               Threads:                         30
2023-05-10 08:38:01,993 - distributed.worker - INFO -                Memory:                  46.57 GiB
2023-05-10 08:38:01,993 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-9j1ke9_n
2023-05-10 08:38:01,993 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:38:02,014 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.56:37266
2023-05-10 08:38:02,014 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:38:02,015 - distributed.core - INFO - Starting established connection to tcp://172.16.3.56:37266
Exception ignored in: <function CachingFileManager.__del__ at 0x2aaacb7a8280>
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 249, in __del__
    self.close(needs_lock=False)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 233, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2570, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
Exception ignored in: <function CachingFileManager.__del__ at 0x2aaacb7a8280>
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 249, in __del__
    self.close(needs_lock=False)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 233, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2570, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
2023-05-10 08:42:23,626 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 32.75 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:25,228 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.128:37079 (pid=159725) exceeded 95% memory budget. Restarting...
2023-05-10 08:42:25,328 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.128:37079 (pid=159725) is slow to accept SIGTERM; sending SIGKILL
2023-05-10 08:42:25,428 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.128:37079 (pid=159725) is slow to accept SIGTERM; sending SIGKILL
2023-05-10 08:42:30,785 - distributed.nanny - INFO - Worker process 159725 was killed by signal 15
2023-05-10 08:42:30,814 - distributed.nanny - WARNING - Restarting worker
2023-05-10 08:42:42,215 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.128:37976
2023-05-10 08:42:42,216 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.128:37976
2023-05-10 08:42:42,216 - distributed.worker - INFO -           Worker name:             SLURMCluster-5
2023-05-10 08:42:42,216 - distributed.worker - INFO -          dashboard at:         172.16.3.128:46590
2023-05-10 08:42:42,216 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.56:37266
2023-05-10 08:42:42,216 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:42:42,216 - distributed.worker - INFO -               Threads:                         30
2023-05-10 08:42:42,217 - distributed.worker - INFO -                Memory:                  46.57 GiB
2023-05-10 08:42:42,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-1p43ucsf
2023-05-10 08:42:42,217 - distributed.worker - INFO - -------------------------------------------------
slurmstepd: error: *** JOB 3085332 ON pn078 CANCELLED AT 2023-05-10T08:42:45 ***
